# 12-1-22 based on https://github.com/rbind/apreshill/blob/main/netlify.toml
[build]
  publish = "public"
  command = "hugo"
  
[build.environment]
  HUGO_VERSION = "0.107.0"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"  
  

    
# old 12-1-22
# [build]
#   publish = "public"
#   command = "hugo"
#   #  command = "hugo --gc --minify -b $URL"
#   
# [build.environment]
#   HUGO_VERSION = "0.107.0"
#   HUGO_ENABLEGITINFO = "true"
# 
# [context.production.environment]
#   HUGO_ENV = "production"
# 
# [context.deploy-preview]
#   command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
# 
# [context.branch-deploy]
#   command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
# 
# [[plugins]]
#   package = "netlify-plugin-hugo-cache-resources"
#   [plugins.inputs]
#     debug = true
